### ISSUE TITLE
Small questions

### ISSUE THREAD

**Issue by pokatomnik** [sigmaSd/PwaIt#1]
Hello! Thank for your script, It's very readable and easy to use.
I am new at building PWAs and I have a small fresh-based project. It's a web app and It can work completely offline.
1) What kind of resources will It store in caches?
2) How can I specify what resources must be cached and what must not?
3) Why didn't you use Workbox?
4) How can I be sure that resources are updated in the cache after application update? You suggested to unregister service worker manually, but this approach is appropriate for developers only, but not for end users.

**Comment by sigmaSd** [comment]
Hello, thanks for your interest

1- it stores *all* requests on the cache <https://github.com/sigmaSd/PwaIt/blob/92fc3f400208bcfaaef4b6b7a8fee3ac2dc35d9d/assets/sw.js#L12>
2- on that same line you can branch and choose to cache or not based on the request
3- I didn't know it existed, but why use a library for something like pwa that the browser natively an simply support, but obviously I don't know that much about workbox, maybe  I change my mind when I check it out
4- The algorithm implemented is pretty straight forward : if there is a network connection it will fetch the resources from the remote and override the cache, you don't need to unregister the service worker, I think that tip is outdated and I'll remove it, but I'm not sure if this way is bullet proof, it just happen to be the easiest way to do updates I found, mdn have a section about updates that I haven't really tested https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers#updates

 More resources:
- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps
- https://whatpwacando.today/

**Comment by pokatomnik** [comment]
Currently I am testing your approach. I could provide feedback from my side.
I've just released few versions of my app using your approach, and cache is updating well with no stale cache issues.
BTW, you probably need to add few lines to manifest file to make PWA installable.
I could make a PR.

**Comment by sigmaSd** [comment]
Good, the pwa is installable as far as I tested, if there is something missing please open a pr and we can discuss it there

**Comment by pokatomnik** [comment]
Please take a look https://github.com/sigmaSd/PwaIt/pull/2
